#!/usr/bin/env nu

# Script to preview what GitHub release assets will be generated
# Usage: nu scripts/preview-release-assets.nu [version]

def main [version?: string] {
    let release_version = if ($version | is-empty) {
        let cargo_content = open Cargo.toml --raw | decode utf-8
        let current_version_line = $cargo_content | lines | where ($it | str starts-with "version = ") | first
        $current_version_line | str replace 'version = "' '' | str replace '"' ''
    } else {
        $version
    }

    print $"🎯 Release Asset Preview for version ($release_version)"
    print "=" * 60
    print ""

    print "📦 Source Code (Auto-generated by GitHub):"
    print $"   • Source code \(zip\)"
    print $"   • Source code \(tar.gz\)"
    print ""

    print "🐧 Linux Assets:"
    print $"   • fcos-ignition-coder-($release_version)-linux-x86_64.tar.gz"
    print $"   • fcos-ignition-coder-($release_version)-linux-x86_64.tar.gz.sha256"
    print $"     └─ System-ready tarball with /usr/local structure"
    print $"     └─ Includes binary, man page, and documentation"
    print ""

    print "🍎 macOS Assets:"
    print $"   • fcos-ignition-coder-macos-x86_64.tar.gz"
    print $"   • fcos-ignition-coder-macos-x86_64.tar.gz.sha256"
    print $"     └─ Intel Mac binary package"
    print $"   • fcos-ignition-coder-macos-aarch64.tar.gz"
    print $"   • fcos-ignition-coder-macos-aarch64.tar.gz.sha256"
    print $"     └─ Apple Silicon Mac binary package"
    print ""

    print "🪟 Windows Assets:"
    print $"   • fcos-ignition-coder-windows-x86_64.zip"
    print $"   • fcos-ignition-coder-windows-x86_64.zip.sha256"
    print $"     └─ Portable Windows binary package"
    print $"   • fcos-ignition-coder-($release_version)-x64.msi"
    print $"   • fcos-ignition-coder-($release_version)-x64.msi.sha256"
    print $"     └─ Professional Windows installer with PATH integration"
    print ""

    print "🐍 Conda Package:"
    print $"   • fcos-ignition-coder-($release_version)-*.tar.bz2"
    print $"   • fcos-ignition-coder-($release_version)-*.tar.bz2.sha256"
    print $"     └─ Cross-platform conda package"
    print ""

    print "📊 Summary:"
    print $"   Total assets: 12 files"
    print $"   Platforms: Linux, macOS \(2 architectures\), Windows"
    print $"   Package formats: Tarball, ZIP, MSI, Conda"
    print $"   Security: SHA256 checksums for all binary assets"
    print ""

    print "🚀 To create this release:"
    print $"   pixi run release ($release_version)"
    print "   or"
    print $"   git tag v($release_version) && git push origin v($release_version)"
    print ""

    print "📋 Installation examples for users:"
    print ""
    print "Windows (MSI):"
    print $"   Download and run: fcos-ignition-coder-($release_version)-x64.msi"
    print ""
    print "Linux (System install):"
    print $"   sudo tar -xzf fcos-ignition-coder-($release_version)-linux-x86_64.tar.gz -C /"
    print ""
    print "macOS:"
    print $"   tar -xzf fcos-ignition-coder-macos-*.tar.gz"
    print $"   sudo cp bin/fcos-ignition-coder /usr/local/bin/"
    print ""
    print "Conda (future):"
    print $"   conda install -c conda-forge fcos-ignition-coder"
}
